#!/usr/bin/env python3
# SS7 Protected Script — Saints7 Development
# Auto-generated by ss7encoder v2.1 — DO NOT MODIFY
import os as _os, sys as _sys
_sys.argv = [__file__] + _sys.argv[1:]

import struct as _st
def _u7(d):
    ol,=_st.unpack_from("<I",d,0)
    pad,=_st.unpack_from("<B",d,4)
    n,=_st.unpack_from("<I",d,5)
    idx=list(_st.unpack_from(f"<{n}I",d,9))
    hs=9+n*4; cs=64
    raw=d[hs:]; ch=[raw[i*cs:(i+1)*cs] for i in range(n)]
    res=[None]*n
    for si,oi in enumerate(idx): res[oi]=ch[si]
    return b"".join(res)[:ol]

def _u6(d):
    k,e=d[:32],d[32:]
    return bytes(b^k[i%32] for i,b in enumerate(e))

def _run():
    _here = _os.path.dirname(_os.path.abspath(__file__))
    _pf   = _os.path.join(_here, "ss7ai.bin")
    if not _os.path.exists(_pf):
        print(f"[ERROR] payload not found: {_pf}"); _sys.exit(1)
    with open(_pf,"rb") as _f: d=_f.read()
    d=_u7(d)
    d=_u6(d)
    import zlib as _zl; d=_zl.decompress(d)
    import marshal as _ms; _co=_ms.loads(d)
    exec(_co,{'__name__':'__main__','__file__':__file__})
_run()
